# Generated by Django 3.2.8 on 2021-10-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanetasApi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('overview_content', models.CharField(max_length=350)),
                ('overview_source', models.URLField(max_length=350)),
                ('structure_content', models.CharField(max_length=350)),
                ('structure_source', models.URLField(max_length=350)),
                ('geology_content', models.CharField(max_length=350)),
                ('geology_source', models.URLField(max_length=350)),
                ('rotation', models.CharField(max_length=50)),
                ('revolution', models.CharField(max_length=50)),
                ('radius', models.CharField(max_length=50)),
                ('temperature', models.CharField(max_length=50)),
                ('img_planet', models.ImageField(upload_to='')),
                ('img_internal', models.ImageField(upload_to='')),
                ('img_geology', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Planeta',
                'verbose_name_plural': 'Planetas',
            },
        ),
    ]
