# Generated by Django 3.2.8 on 2021-10-10 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planetas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planetasapi',
            name='img_geology',
        ),
    ]
