# Generated by Django 3.2.8 on 2021-10-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetas', '0002_remove_planetasapi_img_geology'),
    ]

    operations = [
        migrations.AddField(
            model_name='planetasapi',
            name='img_geology',
            field=models.ImageField(default='wasd', upload_to=''),
            preserve_default=False,
        ),
    ]
