# Generated by Django 3.2.8 on 2021-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetas', '0003_planetasapi_img_geology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planetasapi',
            name='img_geology',
            field=models.ImageField(upload_to='planetas'),
        ),
        migrations.AlterField(
            model_name='planetasapi',
            name='img_internal',
            field=models.ImageField(upload_to='planetas'),
        ),
        migrations.AlterField(
            model_name='planetasapi',
            name='img_planet',
            field=models.ImageField(upload_to='planetas'),
        ),
    ]
